export const metadata = {
  title: "Receita Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <h1>Formulário De Busca</h1>
        {children}
      </body>
    </html>
  );
}
