import { ReactNode } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
// Não passa por montagem,todas as páginas ficaram subordinadas a essa página
interface RootLayout {
  children: ReactNode;
}
//O children é o conteúdo que está sendo passado da página
export default function RootLayout({ children }: RootLayout) {
  console.log("montando layout");

  return (
    // Colocar coisas que serão aparecidas em várias partes do site (deixando mais leve e rápido)
    <html lang="en">
      <body>
        <h1>Página Principal</h1>
        {children}
      </body>
    </html>
  );
}
